[package]
name = "mp"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.62"
anyhow = "1.0.86"
log = "0.4.22"
simple_logger = "5.0.0"
clap = { version = "4.5.9", features = ["derive"] }
